name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  CSV_URL: "train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Check environment variable
      - name: Check Environment Variable
        run: echo $CSV_URL

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run MLflow Project
      - name: Run MLflow Project
        run: |
          mlflow run MLproject --env-manager local

      # Commit mlruns if there are changes
      - name: Save mlruns to repository
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"

          git add mlruns/

          git diff --cached --quiet || git commit -m "Save mlruns from CI run"

          git push origin main
