name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  CSV_URL: "train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Debug repository structure
      - name: Check repository structure
        run: |
          pwd
          ls -R

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run MLflow Project
      - name: Run MLflow Project
        run: |
          mlflow run . --env-manager local

      # Configure Git LFS
      - name: Configure Git LFS
        run: |
          git config --global user.name "${{ secrets.username }}"
          git config --global user.email "${{ secrets.email }}"

          git lfs install
          git lfs track "mlruns/**"

          git add .gitattributes
          git commit -m "Track mlruns with Git LFS" || true

      # Save mlruns
      - name: Save mlruns
        run: |
          git add -f mlruns/

          git commit -m "Save mlruns from CI run" || true

          git push origin main
